### ISSUE TITLE
Hasher 2 - Ideas

### ISSUE THREAD

**Issue by JeysonFlores** [JeysonFlores/hasher#22]
Feature ideas for Hasher 2:
- Handy.Deck navigation between views
- More algorithms?
- New UI design [needs work]
- New logo?

**Comment by dreamcat4** [comment]
Hey there,
Just stumbled across your utility today. And I have some relevant feedback here.

ATM i am using an extension for `nemo` file manager. Whereby it adds a new tab inside of a file's properties. And then when you manually click the Hash! button. It will then go ahead and generate all of the popular hashes and populate a table.

However to improve further upon this idea... it would be to have a setting whereby you can tell the program to auto hash for files under a certain size.

Then if the file is a large one. And it's bigger than X megabytes. Then it will automatically notice. And not bother automatically hashinging it immediately. And instead deselect all of the hashes. Then the user much choose which one(s) to select in a more granular and manual way.

I feel this is generally the way to go for the most part. This is probably the best kind of compromise, with the least friction.

In terms of UI, well just look at the nemo plugin. And iterate from that point forwards. But you can also look on windows for other file hashing GUI program(s). Because they have some good ones over there too. In fact probably the nemo plugin was a recreation itself of something else even better.

Hope you found the feedback was helpful, good day

**Comment by JeysonFlores** [comment]
Hey @dreamcat4 thanks for your opinion and sorry for taking too long to answer. 
Originally I wanted this app to perform similar duties to what you are describing, however I only had a weekend to write it and I didn't know so much about Gtk development. I hope soon I can make a refurbishing of this app and I'd like to apply the majority of the things you're describing.
I have some questions however, I've never used the `nemo` file manager and I don't even know what plugin you're referring to, so, Would you mind to share some screenshots or images about the UI side of your proposals? Thanks.

**Comment by dreamcat4** [comment]
```sh
nemo-gtkhash/hirsute,now 1.2-1build2 amd64 [installed]
```


![Screenshot from 2021-12-01 08-42-47](https://user-images.githubusercontent.com/63074/144201165-f6aa891b-3ad2-4eb9-af77-580bb70f8de3.png)


![Screenshot from 2021-12-01 08-43-11](https://user-images.githubusercontent.com/63074/144201190-3ff96a10-cb38-4f20-9e09-2c0c6352e653.png)

**Comment by JeysonFlores** [comment]
I'll be start working on this asap. However I'll probably have to rewrite the entire project, so I'll take advantage of that and I'll make a more sustainable base for future updates.

**Comment by dreamcat4** [comment]
ok cool man! wishing you the best of luck with all those longer term efforts. just you know - don't take this app too seriously and have fun! because it's a GUI convenience tool after all. so if things end up being too difficult to implement no worries! nobody is holding you to such obligation (we can still fallback to cmdline on linux and do same stuff)

this is speaking as somebody who randomly inherited an ancient legacy graphical `alt+tab` switcher X app. which was a complete rats nest / mess and couldn't keep up maintenance of it. Just couldn't implement the more ambitious grander ideas in the end

what elsewhere occurs to me about your app to bring up though?

well if you can make your standalone program somehow integrate with a finder / file manager (explorer.exe) type of apps. for example like nautilus or alternatives. Then that would be a great way to reuse a same single shared codebase. Without having to write everything twice over. And then maybe it would end up being a bigger uptake / larger user scale user adoption. But that is also something depending on how is the larger ecosystem. And what opportunities are out there. For what is actually possible to do in the context of those other existing programs (which dont already adequately have their own built in hashing functionality). So the ease of achieving something a bit grander like that. It simple might be unfeasible and out of the question. So this was not any specific feature request or anything. Just seemed like a cool observation to bring up BTW / FYI. It's not any important matter or anything. Just a food for thought

**Comment by JeysonFlores** [comment]
Don't worry dude. As I said before I wrote this app literally in a weekend with no previous experience on Gtk programming, I finished it but the code I wrote it's a mess, I knew that if I wanted to make changes to it I would have to rewrite it. The good news is that it's not really a large application. I have more experience in Gtk so I hope I can do a better job.
